#!/bin/bash

cd $OPENSHIFT_REPO_DIR

. ".openshift/vertx-module-registry.config"

cd $OPENSHIFT_DATA_DIR

# Install Vert.x if needed

if [[ -d vert.x-${VERTX_VERSION} ]]; then
	echo "Vert.x ${VERTX_VERSION} already installed."
else
    # Cleanup old versions if Vert.x
	for version in vert.x-*; do 
		echo "Removing $version"
		rm -rf $version 
	done

	echo "Installing Vert.x $VERTX_VERSION"

  echo "Downloading http://vert-x.github.io/vertx-downloads/downloads/vert.x-${VERTX_VERSION}.tar.gz"
  curl --insecure -o vert.x-${VERTX_VERSION}.tar.gz "http://vert-x.github.io/vertx-downloads/downloads/vert.x-${VERTX_VERSION}.tar.gz"
  tar -xf vert.x-${VERTX_VERSION}.tar.gz
  rm vert.x-${VERTX_VERSION}.tar.gz

fi
