#!/bin/bash

cd $OPENSHIFT_REPO_DIR

. ".openshift/vertx-module-registry.config"

cd $OPENSHIFT_REPO_DIR

echo "Starting Vert.x application!"

vertx runmod ${MODULE_NAME} -conf "${OPENSHIFT_DATA_DIR}/config.json" &> "${OPENSHIFT_DIY_LOG_DIR}vert.x.log" &
echo $! > ${OPENSHIFT_DATA_DIR}/application.pid

